version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: comment-system-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16.8-alpine
    container_name: comment-system-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    

volumes:
  postgres-data:
