version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: comment-system-app
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./main", "--storage=db"]

  db:
    image: postgres:16.8-alpine
    container_name: comment-system-db    
    environment:
      - POSTGRES_USER=ozon_keker  # your
      - POSTGRES_PASSWORD=1234    # your
      - POSTGRES_DB=comm_sys_db   # your
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    

volumes:
  postgres-data:
