// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommEdge struct {
	Node   *Comment `json:"node"`
	Cursor string   `json:"cursor"`
}

type Comment struct {
	ID        string  `json:"id"`
	AuthorID  string  `json:"authorID"`
	Content   string  `json:"content"`
	CreatedAt string  `json:"createdAt"`
	Rating    int32   `json:"rating"`
	PostID    string  `json:"postID"`
	ParentID  *string `json:"parentID,omitempty"`
}

type CommentsConnection struct {
	Edges    []*CommEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type Post struct {
	ID         string              `json:"id"`
	AuthorID   string              `json:"authorID"`
	Title      string              `json:"title"`
	Content    string              `json:"content"`
	AllowComms bool                `json:"allowComms"`
	CreatedAt  string              `json:"createdAt"`
	Rating     int32               `json:"rating"`
	Comments   *CommentsConnection `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Email    *string    `json:"email,omitempty"`
	Posts    []*Post    `json:"posts"`
	Comments []*Comment `json:"comments"`
}
